name: Test 

on:
  workflow_dispatch:
  pull_request:

jobs:
  test_with_prefix_job:
    runs-on: ubuntu-latest
    name: A job to test action with prefix
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: JSON to variables
      uses: ./
      with:
        filename: 'test.json'
        prefix: test
    - name: Show output
      run: echo "The time was ${{ env.test_value }}, ${{ env.test_array_0_value }}, ${{ env.test_obj_value1 }}"

  test_without_prefix_job:
    runs-on: ubuntu-latest
    name: A job to test action without prefix
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: JSON to variables
      uses: ./
      with:
        filename: 'test.json'
    - name: Show output
      run: echo "The time was ${{ env.value }}, ${{ env.array_0_value }}, ${{ env.obj_value1 }}"

